version: "3.11"

services:
  block_explorer:
    image: block_explorer
    container_name: block_explorer
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./app:/code/app