version: "3.11"

services:
  block_explorer:
    image: block_explorer
    container_name: block_explorer
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./app:/src/app
    command: ["--reload"]

  test:
    image: block_explorer
    container_name: block_explorer_test
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./app:/src/app
    entrypoint: ["pytest", "app"]
