on:
  pull_request:
    branches: [main]

name: Block Explorer CI

jobs:
  ci:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        id: test
        run: make ci
